/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.demo.gui;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Maria Paz Puerta
 */
public class Casa extends javax.swing.JFrame {

    /**
     * Creates new form Casa
     */
    public Casa() {
        initComponents();
        this.setSize(419, 385);
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public void paint(Graphics g){
        
        g.setColor(Color.BLUE); // Casa principal
        g.fillRect(100, 150, 200, 150);
       
        
        // Techo
        int[] x = {100, 200, 300};
        int[] y = {150, 50, 150};
        g.setColor(new Color(139, 69, 19));
        g.fillPolygon(x, y, 3);
        
        g.setColor(Color.GREEN); // Puerta
        g.fillRect(175, 220, 50, 80);
        
        g.setColor(Color.BLACK); // Manija de la puerta
        g.fillOval(210, 250, 15, 15);
        
        g.setColor(Color.WHITE); // Ventana 1
        g.fillRect(120, 170, 30, 30);
        
        g.setColor(Color.WHITE); // Ventana 2
        g.fillRect(250, 170, 30, 30);
        
        g.setColor(new Color(173, 216, 230)); // Subventana 1
        g.fillRect(125, 175, 20, 20);
        
        g.setColor(new Color(173, 216, 230)); // Subventana 2
        g.fillRect(255, 175, 20, 20);
        
        g.setColor(new Color(0, 100, 0)); // Árbol
        g.fillOval(50, 180, 50, 50);
        
        g.setColor(new Color(139, 69, 19)); // Tronco
        g.fillRect(65, 230, 50, 50);
        
        g.setColor(Color.YELLOW); // Sol
        g.fillOval(350, 30, 60, 60);
        
        g.setColor(new Color(0, 100, 0)); // Pasto
        g.fillRect(0, 300, 419, 120);
        
    }  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Casa casa = new Casa();
        casa.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
